
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: gitwebhook-operator
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: gitwebhook-operator-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: gitwebhook-operator
    app.kubernetes.io/part-of: gitwebhook-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: https
      scheme: https
      tlsConfig:
        ca: 
          secret:
            key: 'tls.crt'
            name: gitwebhook-operator-certs
            optional: false
        serverName: $(METRICS_SERVICE_NAME).$(METRICS_SERVICE_NAMESPACE).svc
  selector:
    matchLabels:
      control-plane: gitwebhook-operator
