apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: gitwebhook-operator
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: gitwebhook-operator
    app.kubernetes.io/part-of: gitwebhook-operator
    app.kubernetes.io/managed-by: kustomize
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: gitwebhook-operator-certs    
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: gitwebhook-manager
